version: '2.0'
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /mnt/data/docker:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
    image: brennerm/docker-registry-frontend
    ports:
      - 8080:80
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net: